# Generated by Django 2.2 on 2020-09-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coronaTelangana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('positiveCases', models.CharField(max_length=200)),
                ('negativeCases', models.CharField(max_length=200)),
                ('deaths', models.CharField(max_length=200)),
                ('caseFatalityRate', models.CharField(max_length=200)),
                ('recoveryRate', models.CharField(max_length=200)),
                ('homeIsolation', models.CharField(max_length=200)),
                ('samplesTested', models.CharField(max_length=200)),
            ],
        ),
    ]
