# Generated by Django 2.2 on 2020-09-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coronaDist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('positiveCases', models.CharField(max_length=200)),
            ],
        ),
    ]
