# Generated by Django 2.2 on 2020-09-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_coronadist'),
    ]

    operations = [
        migrations.CreateModel(
            name='coronaLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('centers', models.CharField(max_length=2000)),
            ],
        ),
    ]
